### ISSUE TITLE
[proposal] 우산 번호 선택 시 드롭다운 버튼 개선 제안

### ISSUE THREAD

**Issue by oh2o** [YeonSeong-Lee/OpenUmbrella#1]
안녕하세요! 서비스 잘 쓰고 있습니다.
현재 우산 번호 수동 선택을 드롭다운으로 해야하는데,
우산 개수가 많다보니 뒷 번호를 골라야할수록 스크롤을 많이 해야해서 불편합니다.
다른 방법이 도입되면 더 편하게 이용할 수 있을 것 같아요~
감사합니다.

**Comment by YeonSeong-Lee** [comment]
좋은 제안 감사합니다.

---

드랍다운 말고 특별히 적절할것이라고 생각하시는 형태가 있을까요?

**Comment by YeonSeong-Lee** [comment]
![20230826_180747.jpg](https://github.com/YeonSeong-Lee/OpenUmbrella/assets/62806979/7ebbe2b0-87f5-4ff1-b311-7740b502f9ca)

qr 대출이 조금 더 용이할 수 있도록 실물 안내 qr추가 하였습니다.

**Comment by YeonSeong-Lee** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Web_NFC_API

---

추후 2차개발단계에서 nfc 태깅을 이용한 대출/반납 방법을 고려하도록 하겠습니다.

현재 사용자들의 주요 브라우져인 크롬과 삼성 인터넷에서 사용가능합니다.
![image](https://github.com/YeonSeong-Lee/OpenUmbrella/assets/62806979/50e7c79a-6413-479b-8ebf-7a7f6defda9b)

**Comment by oh2o** [comment]
안녕하세요. 답변 감사합니다. 답장을 이제 봤네요 😅

저라면 간단하게 대출하고자 하는 우산 숫자를 기입할 것 같습니다.
그리고 디폴트로 현재 대여 가능한 우산 중 맨 앞 번호의 우산을 띄워줘도 좋겠다고 생각했어요.
만약 해당 우산이 상태가 좋지 않거나 실제로 없다면 그 다음 번호로 넘어가는 식도 좋을 것 같다고 생각했습니다. (이 경우는 넘어가야하는 경우가 많다면 오히려 귀찮아서 별로일 수도 있을 것 같습니다.)
이런 방식을 생각한 이유는 결국 다 똑같은 우산이니까 최대한 아무것도 하지 않고 빠르게 아무거나 빌리기만 하면 된다고 생각하기 때문입니다.

지난 번 사용해보니 폰을 들어서 qr을 찍는 과정 자체가 귀찮다고 느껴서 순전히 제 느낀 점에 기반해서 작성한 것이고,
실제 다른 사람들은 편리하다고 느꼈을 수도 있을 거라고 생각합니다. 

지속적으로 소식 들려주셔서 감사합니다^^

ps. 이유가 궁금할 수도 있을 것 같아서 추가했습니다

**Comment by YeonSeong-Lee** [comment]
@oh2o 9월 달 중에 말씀하신 내용 반영하여, 드랍다운 부분 개선하도록 하겠습니다.

유용한 피드백 감사드립니다!
