### ISSUE TITLE
원치 않는 qr코드가 인식돼요. 버튼으로 qr코드가 원하는 순간 인식되게 바꿔주세요

### ISSUE THREAD

**Issue by mikim3** [YeonSeong-Lee/OpenUmbrella#2]
그럼 경험상 인식률은 떨어지지만 QR코드 자체가 인식률이 좋아서 괜찮을 겁니다.

**Comment by YeonSeong-Lee** [comment]
resolved 6e11a6c18a0bbada1d46d68be6634e8dfb53d284
