### ISSUE TITLE
가능한 많은 화면에서 제대로 나오게끔 개선

### ISSUE THREAD

**Issue by mikim3** [YeonSeong-Lee/OpenUmbrella#7]
문제와 관련된 기능 요청인가요? 설명해주세요.
1. QR이 나오는 페이지에서 사용자들의 불만이 굉장히 많았습니다.  해당페이지를 개선해야 되겠습니다.
2. 특정 기종에서는 버튼이 스크롤을 내려야지만 나옵니다.

원하는 솔루션을 설명해주세요.
일단 모든 문제의 원인이 되는 QR코드를 밑으로 내리고 체크박스를 위로 올리겠습니다.
QR코드 페이지에서 Nav를 포함한 모든 화면이 모든 디바이스에서 한 화면에 나오도록 바꿔야 되겠습니다.

**Comment by YeonSeong-Lee** [comment]
good
